#pragma once

#include "ConfigDllExportUIManagement.h"
#include <QtWidgets/QDialog>
#include "MotionHubUtil/Console.h"
#include "MotionHubUtil/InputManager.h"
#include "QtCore/qstringlistmodel.h"
#include "QtCore/qstring.h"
#include "QtWidgets/qlistview.h"

#include "TrackerManagement/TrackerManager.h"


namespace Ui {
	class CreateTrackerWindow;
}

/*!
 * 
 * \class CreateTrackerWindow
 * 
 * \brief dialog for creating new trackers
 * 
 * \author Kester Evers and Eric Jansen
 * 
 */
class UIManagement_DLL_import_export CreateTrackerWindow : public QDialog
{
	Q_OBJECT
public:
	/*!
	 * default constructor 
	 */
	explicit CreateTrackerWindow(InputManager* inputManager, TrackerManager* trackerManager, QListView* listViewTracker, QWidget *parent = 0);
	~CreateTrackerWindow();

private slots:
	/*!
	 * slot for button create 
	 */
	void slotCreateTracker();
	/*!
	 * 
	 * slot for dropdown selection
	 * 
	 * \param id selected tracker id
	 */
	void switchTrackerType(int id);

private:
	/*!
	 * qt class generated by the moc 
	 */
	Ui::CreateTrackerWindow *ui;
	/*!
	 * reference to the inputManager 
	 */
	InputManager* m_refInputManager;

	TrackerManager* m_refTrackerManager;
	/*!
	 *  reference to the tracker list in main window
	 */
	QListView* m_refListViewTracker;

	int m_selectedTrackerIdInDropdown = 0;

};