#pragma once

#include "ConfigDllExportUIManagement.h"
#include <QtWidgets/QMainWindow>
#include "MotionHubUtil/Console.h"
#include "CreateTrackerWindow.h"
#include "QtCore/qstringlistmodel.h"
#include "QtCore/qstring.h"
#include "QtWidgets/qtreewidget.h"

#define GET_VARIABLE_NAME(Variable) (#Variable)


#include <chrono>
#include <atomic>
#include <list>

namespace Ui
{
	class MainWindow;
}

/*!
 * \class MainWindow
 * 
 * \brief Qt main Window wrapper containing slot methods
 * 
 * \author Eric Jansen and Kester Evers
 * 
 */
class UIManagement_DLL_import_export MainWindow : public QMainWindow
{
	Q_OBJECT
public:

	/*!
	 * default constructor  
	 */
	explicit MainWindow(TrackerManager* trackerManager, QWidget *parent = 0);
	/*!
	 * default destructor 
	 */
	~MainWindow();


private slots:
	/*!
	 * slot for start/stop button 
	 */
	void slotToggleTracking();
	/*!
	 * slot for "add" tracker button 
	 */
	void slotAddTracker();
	/*!
	 * slot for "remove" tracker button
	 */
	void slotRemoveTracker();
	void on_actionExit_triggered();
	void slotSelectTracker(QModelIndex index);

private:
	/*!
	 * qt class generated by the moc
	 */
	Ui::MainWindow *ui;

	TrackerManager* m_refTrackerManager;
	/*!
	 * createTracker dialog 
	 */
	CreateTrackerWindow* m_createTrackerWindow;
	/*!
	 *  tracking state for changing icon
	 */
	bool m_isTracking = false;

	std::list<QTreeWidgetItem*> m_topLevelItemPool;

	void toggleIconStartButton();

	void update();

	void updateHirachy();

	std::thread* m_updateThread;

	std::map<std::pair<std::string, int>, Tracker*>* m_refTrackerPool;

	std::atomic<bool> m_isHirachyLocked = false;

	int m_selectedTrackerInList;

	void updatePropertiesInInspector();
	void insertPropertiesIntoInspector();
	void removePropertiesFromInspector();

	void addRowToInspector(std::string propertyName, std::string valueName);
};